proxy: False
proxy_ip_port: 35.236.207.242:33333
thread_number: 1
max_attempts: 4
delay_attempts: 10
timeout: 30
output_dir: C:\Users\LNKIZ\Desktop\testScrapingHLibertad\auto_scraping_libertad\salida
categories_url: https://www.hiperlibertad.com.ar/api/catalog_system/pub/category/tree/3