BRANCHES = [ # comentados para pruebas
     # {'nombre': 'Córdoba - Lugones',
     # 'codigo': 1},
     # {'nombre': 'Córdoba - Libertad FAN Rivera',
     # 'codigo': 2},
     # {'nombre': 'Córdoba - Jacinto Rios',
     # 'codigo': 3},
     {'nombre': 'Córdoba - Ruta 9',
     'codigo': 4}
     # {'nombre': 'Córdoba - Villa Maria',
     # 'codigo': 5},
     # {'nombre': 'Mendoza - Godoy Cruz',
     # 'codigo': 6},
     # {'nombre': 'Misiones - Posadas',
     # 'codigo': 7},
     # {'nombre': 'Tucumán - 1',
     # 'codigo': 8},
     # {'nombre': 'Tucumán - 2',
     # 'codigo': 9},
     # {'nombre': 'Chaco',
     # 'codigo': 10},
     # {'nombre': 'Santa Fé - Rosario',
     # 'codigo': 11},
     # {'nombre': 'Sgo del Estero',
     # 'codigo': 12},
     # {'nombre': 'San Juan',
     # 'codigo': 13},
     # {'nombre': 'Salta',
     # 'codigo': 14},
     # {'nombre': 'Santa Fe - Rafaela',
     # 'codigo': 15},
     # {'nombre': 'Mendoza - Tienda Digital Mza Capital',
     # 'codigo': 16},
     ]